### ISSUE TITLE
Please update for 1.14.1

### ISSUE THREAD

**Issue by andris155** [Realizedd/Duels#16]
```
[15:31:46] [Server thread/INFO]: [Duels] Enabling Duels v3.2.3
[15:31:46] [Server thread/WARN]: [Duels] Failed to hook into CombatLogX: This version of CombatLogX is not supported. Please try upgrading to the latest version.
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'Essentials'!
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'mcMMO'!
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'MyPet'!
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'PlaceholderAPI'!
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'Vault'!
[15:31:46] [Server thread/INFO]: [Duels] Successfully hooked into 'WorldGuard'!
[15:31:46] [Server thread/INFO]: [Duels] ArenaManager: Loaded 0 arena(s).
[15:31:46] [Server thread/ERROR]: Error occurred while enabling Duels v3.2.3 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
	at me.realized.duels.util.gui.MultiPageGui$PageNode.setTitle(MultiPageGui.java:231) ~[?:?]
	at me.realized.duels.util.gui.MultiPageGui$PageNode.setEmpty(MultiPageGui.java:198) ~[?:?]
	at me.realized.duels.util.gui.MultiPageGui.calculatePages(MultiPageGui.java:76) ~[?:?]
	at me.realized.duels.arena.ArenaManager.handleLoad(ArenaManager.java:95) ~[?:?]
	at me.realized.duels.DuelsPlugin.load(DuelsPlugin.java:242) ~[?:?]
	at me.realized.duels.DuelsPlugin.onEnable(DuelsPlugin.java:173) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-20]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:31:46] [Server thread/INFO]: [Duels] Disabling Duels v3.2.3
```

**Comment by Realizedd** [comment]
It’s being worked on. A dev build of 1.14 is available on my discord server under #dev-builds.
