### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by successed** [Realizedd/Duels#27]
[10:00:40 WARN]: [Duels] Task #120 for Duels v3.3.0 generated an exception
java.lang.NullPointerException: null
        at me.realized.duels.data.LocationData.<init>(LocationData.java:20) ~[?:?]
        at me.realized.duels.data.LocationData.<init>(LocationData.java:24) ~[?:?]
        at me.realized.duels.data.LocationData.<init>(LocationData.java:30) ~[?:?]
        at me.realized.duels.data.ArenaData.<init>(ArenaData.java:22) ~[?:?]
        at me.realized.duels.arena.ArenaManager.saveArenas(ArenaManager.java:127) ~[?:?]
        at me.realized.duels.arena.ArenaManager.lambda$handleLoad$27(ArenaManager.java:104) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-226]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Realizedd** [comment]
A world that contained some arenas is no longer existing. Stop the server and remove those arenas from arenas.json and things should work fine.
