### ISSUE TITLE
UPDATE 1.15.1 PLUGİN NOT WORK ON

### ISSUE THREAD

**Issue by successed** [Realizedd/Duels#29]
[08:04:16 WARN]: [Duels] Task #125 for Duels v3.3.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
        at me.realized.duels.data.ItemData.<init>(ItemData.java:167) ~[?:?]
        at me.realized.duels.data.KitData.<init>(KitData.java:20) ~[?:?]
        at me.realized.duels.kit.KitManager.saveKits(KitManager.java:115) ~[?:?]
        at me.realized.duels.kit.KitManager.lambda$handleLoad$32(KitManager.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-32]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-32]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Drc-DEV** [comment]
I fixed this in my PR https://github.com/Realizedd/Duels/pull/30

**Comment by Realizedd** [comment]
Fixed in bb57ba7.
