### ISSUE TITLE
Could not pass event BlockCanBuildEvent

### ISSUE THREAD

**Issue by dogi-dogi** [Realizedd/Duels#65]
**just anyblock place error**

v 1.12.2 paper

[05:29:39 ERROR]: Could not pass event BlockCanBuildEvent to Duels v3.5.1
org.bukkit.event.EventException: null
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[Paper.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.a(World.java:2781) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ItemBlock.a(ItemBlock.java:23) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:191) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.block.BlockCanBuildEvent.getPlayer()Lorg/bukkit/entity/Player;
        at me.realized.duels.spectate.SpectateManagerImpl$SpectateListener.on(SpectateManagerImpl.java:393) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[Paper.jar:git-Paper-1618]
        ... 19 more

**Comment by SquaredStudios-MC** [comment]
Also a bug on 1.8.8 Spigot. Happens to me when i place a block.

**Comment by DB20-official** [comment]
![image](https://user-images.githubusercontent.com/26073967/156060959-08285363-50de-4166-8d2c-f1310f145949.png)
Same error here too. Happens on Paper 1.12.2.

**Comment by Realizedd** [comment]
Fixed in 621d0d5. Sorry for the delay!
