### ISSUE TITLE
All Arenas are full.

### ISSUE THREAD

**Issue by ultra-black** [Realizedd/Duels#73]
Whenever I go into a duel, it works the first time however the second time it fills up all the arenas when no one is in there. It fills up all the queues

**Comment by ultra-black** [comment]
Hmm it seems like letting it choose a random arena caused this..

**Comment by ultra-black** [comment]
Plug-ins: AdvancedBan, AuctionHouse, BeautyQuests, BetterTeams, BountyPlus*, Citizens, Coins, CombatLogX, CoreProtect, DeluxeHub, DiscordSRV, Duels, Essentials, FakePlayer, FarmProtection, GSit, LightAntiCheat, LuckPerms, Maintenance, Multiverse-Core, Multiverse-Inventories, Orebfuscator, PlaceholderAPI, ProtocolLib, ProtocolSupport, ServerListPlus*, SimpleScore, SirBlobmanCore (SirBlobmanAPI, XSeries), SkBee, Skript, StayPut*, SuperVanish, TabList, TimeIsMoney, TradeSystem, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, VoidGen, WorldEdit, WorldGuard

**Comment by Realizedd** [comment]
There is most likely going to be an error on console or in Duels log (plugins/Duels/logs). Could you post it?

**Comment by ultra-black** [comment]
SEVERE] There was an error while unloading DuelManager! If you believe this is an issue from the plugin, please contact the developer.
java.lang.NullPointerException: Cannot invoke "me.realized.duels.player.PlayerInfo.getExtra()" because "info" is null
	at Duels-3.5.2.jar//me.realized.duels.duel.DuelManager.handleWin(DuelManager.java:273)
	at Duels-3.5.2.jar//me.realized.duels.duel.DuelManager.handleUnload(DuelManager.java:169)
	at Duels-3.5.2.jar//me.realized.duels.DuelsPlugin.unload(DuelsPlugin.java:282)
	at Duels-3.5.2.jar//me.realized.duels.DuelsPlugin.reload(DuelsPlugin.java:330)
	at Duels-3.5.2.jar//me.realized.duels.command.commands.duels.subcommands.ReloadCommand.execute(ReloadCommand.java:41)
	at Duels-3.5.2.jar//me.realized.duels.util.command.AbstractCommand.lambda$register$0(AbstractCommand.java:139)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:833)
[22-05-20 21:32:36] [INFO] [DEBUG] onDisable start -> 1653071556968
