### ISSUE TITLE
This Power

### ISSUE THREAD

**Issue by lensfort** [Realizedd/Duels#92]
[15:10:12 WARN]: [Duels] Task #283688 for Duels v3.5.2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.power" is null
	at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaFirework.getPower(CraftMetaFirework.java:392) ~[paper-1.19.3.jar:git-Paper-362]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftFirework.setFireworkMeta(CraftFirework.java:66) ~[paper-1.19.3.jar:git-Paper-362]
	at me.realized.duels.duel.DuelManager$DuelListener.lambda$on$4(DuelManager.java:569) ~[Duels-3.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-362]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-362]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-362]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-362]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-362]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-362]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-362]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by lensfort** [comment]
The winner is stuck in the duel and /duels reload is needed to get them back

**Comment by lensfort** [comment]
It seems that turning off the option for fireworks spawn at winner within config has worked around this issue.

**Comment by DevSolaris** [comment]
Hey @lensfort, this is fixed in Paper build 366.
