### ISSUE TITLE
[Duels] Task#33 for Duels v3.5.2 generated an exception

### ISSUE THREAD

**Issue by NopeProsOnly** [Realizedd/Duels#95]
```
[13:06:49 WARN]: [Duels] Task #33 for Duels v3.5.2 generated an exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register me.realized.duels.duel.DuelManager$DuelListener@41e9bc38 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at me.realized.duels.duel.DuelManager.lambda$new$0(DuelManager.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[13:06:49 WARN]: [Duels] Task #32 for Duels v3.5.2 generated an exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register me.realized.duels.player.PlayerInfoManager$PlayerInfoListener@5e703fcf while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at me.realized.duels.player.PlayerInfoManager.lambda$new$0(PlayerInfoManager.java:70) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

I tried to reload the plugins, then the plugin just stopped. I restarted the server and this happens.

**Comment by NopeProsOnly** [comment]
Ah. This happens when you edit the kits.yml and miss a comma
